### ISSUE TITLE
Could not find MPFR

### ISSUE THREAD

**Issue by tingyucheng** [iic-jku/ibm_qx_mapping#1]
Hello. I am new to quantum computer and want to try your code to learn about IBM QX architecture mapping. However, although I installed VirtualBox and Ubuntu to compile these files, I got this error：
Could not find MPFR (missing: MPFR_INCLUDES MPFR_LIBRARIES MPFR_VERSION_OK)
(Required is at leaast version "1.0.0")
Call Stack  (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindMPFR.cmake:70 (find_package_handle_standard_args)
  CMakeLists.txt:8 (FIND_PACKAGE)

I had spent lots of time on finding the problem, but I still don't know how to solve it, and wonder whether I had to install any other library and how should I do. Thanks.

**Comment by hillmich** [comment]
Hi,

you should be able to easily get the required depencies by executing

```
sudo apt install libmpfrc++-dev
```

in the terminal.

Please let us know, if this solved the issue.

**Comment by tingyucheng** [comment]
Thanks for your reply. I tried the command and got this error：

> Could NOT find MPFR (missing: MPFR_LIBRARIES) (Required is at leaast version "1.0.0")
> Call Stack (most recent call first):
>   /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
>   cmake/Modules/FindMPFR.cmake:70 (find_package_handle_standard_args)
>   CMakeLists.txt:8 (FIND_PACKAGE)

It seems to solve the problem of missing "MPFR_INCLUDES" and "MPFR_VERSION_OK", but still missing "MPFR_LIBRARIES".

**Comment by hillmich** [comment]
Well I don't know why it's not working for you.
Anyway, MPFR is not really required for the mapper, so the newest commit doesn't use it anymore.

Please let us know if this worked for you.

**Comment by tingyucheng** [comment]
Again, thanks for your prompt reply. I modified the code as the commit, but I got the same result of missing MPFR_LIBRARIES and some other failed on detecting C and CXX compiler features.

> CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:186 (configure_file):
>   configure_file Problem configuring file
> Call Stack (most recent call first):
>   CMakeLists.txt:2 (project)
> 
> 
> -- The C compiler identification is GNU 7.3.0
> CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCCompiler.cmake:192 (configure_file):
>   configure_file Problem configuring file
> Call Stack (most recent call first):
>   CMakeLists.txt:2 (project)
> 
> 
> -- The CXX compiler identification is GNU 7.3.0
> CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:190 (configure_file):
>   configure_file Problem configuring file
> Call Stack (most recent call first):
>   CMakeLists.txt:2 (project)
> 
> 
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - failed
> -- Detecting C compile features
> -- Detecting C compile features - failed
> CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:72 (configure_file):
>   configure_file Problem configuring file
> Call Stack (most recent call first):
>   CMakeLists.txt:2 (project)
> 
> 
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - failed
> -- Detecting CXX compile features
> -- Detecting CXX compile features - failed
> CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:65 (configure_file):
>   configure_file Problem configuring file
> Call Stack (most recent call first):
>   CMakeLists.txt:2 (project)
> 
> 
> CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
>   Could NOT find MPFR (missing: MPFR_LIBRARIES) (Required is at least version
>   "1.0.0")
> Call Stack (most recent call first):
>   /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
>   cmake/Modules/FindMPFR.cmake:70 (find_package_handle_standard_args)
>   CMakeLists.txt:8 (FIND_PACKAGE)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/myubuntu/Documents/data/ibm_qx_mapping-master/build/CMakeFiles/CMakeOutput.log".
> See also "/home/myubuntu/Documents/data/ibm_qx_mapping-master/build/CMakeFiles/CMakeError.log".

I feel that it doesn't make sense... 
I think I will keep trying to find other method to install MPFR_LIBRARIES and will let you know if I have any progress as well.

**Comment by hillmich** [comment]
Could you please pull the latest commit and try once more (without MPFR)?

I accidently missed a line in the CMakeList.txt still referring to MPFR, but it's gone now.

**Comment by tingyucheng** [comment]
It works!! Thank you!
