### ISSUE TITLE
Run fails: 'Failed to open file 'qelib1.inc'

### ISSUE THREAD

**Issue by diogovalada** [iic-jku/ibm_qx_mapping#2]
When trying to run one of the example files, right after compiling the program, I get the following error:

```
$ ./build/ibm_qx_mapping examples/4gt10-v1_81.qasm
Failed to open file 'qelib1.inc'!
Undefined gate: x
Undefined gate: q
ERROR: unexpected statement: started with [!
```

I am running it under Linux 64bit.

Thanks
Diogo

**Comment by hillmich** [comment]
Hi,

you can find the missing file in the [Qiskit repo](https://github.com/Qiskit/openqasm/blob/master/examples/generic/qelib1.inc). You have to place it in the working directory from where you start the executable and it should work fine.

Cheers,
Stefan

**Comment by diogovalada** [comment]
Hi, thanks, I thought I had posted  a follow up for this issue.
I found the missing file in the examples folder, in this repo. It worked.

The funny this is, previously I tried to use the qelib1.inc present in Qiskit-Terra, and it failed, with a token related error message...

**Comment by ghost** [comment]
The current version does not work alone without ibm qiskit ?

**Comment by azulehner** [comment]
The current version works without IBM Qiskit. The executable has to be launched from a directory that includes the qelib1.inc file with the definition of gates like h, t, ...

**Comment by ghost** [comment]
> The current version works without IBM Qiskit. The executable has to be launched from a directory that includes the qelib1.inc file with the definition of gates like h, t, ...

Do you mean that anyway the file "qelib1.inc" should be placed ?
I remember an earlier version correctly worked without the file.

**Comment by azulehner** [comment]
You have to place the file in the directory from which you start the program if the .qasm file you try to map a .qasm file that contains the statement `include "qelib1.inc";`. If you do not have an include statement, the file is obviously not needed. The file can be found in the folder **examples** of this repository.

**Comment by ghost** [comment]
Thank you, azulehner.

So far I had tested your earlier version which works well as stand alone without the file.
(To be honest, I do not know the previous version really does not require the file, but I didn't check the file to run your mapper.)

Recently, I recognized that a new version was uploaded.
When I tested it, some error with the file happened. (Still, the previous version works well in the same laptop.)
In this regards, I have asked.
