### ISSUE TITLE
unrolled U gate cannot be recognized by qiskit

### ISSUE THREAD

**Issue by ZchiPitt** [iic-jku/ibm_qx_mapping#3]
I ran ibm_qx_mapping to generate mapping for qft_10.qasm, the generated code is like below

`OPENQASM 2.0;`
`include "qelib1.inc";`
`qreg q[16];`
`creg c[16];`
`U(1.570796, 0.000000, 3.141593) q[0];`
`U(0.000000, 0.000000, -0.785400) q[0];`
`CX q[0],q[1];`
`U(0.000000, 0.000000, 0.785400) q[0];`
`CX q[0],q[1];`
`U(0.000000, 0.000000, -0.392700) q[0];`
`U(1.570796, 0.000000, 3.141593) q[1];`
`CX q[1],q[2];`
`U(pi/2,0,pi) q[1];`
`U(pi/2,0,pi) q[2];`
`CX q[1],q[2];`
`U(pi/2,0,pi) q[1];`
`U(pi/2,0,pi) q[2];`
`CX q[1],q[2];`
`CX q[0],q[1];`
`U(0.000000, 0.000000, -0.785400) q[2];`
`U(0.000000, 0.000000, 0.392700) q[0];`
`CX q[0],q[1];`
`U(0.000000, 0.000000, -0.196350) q[0];`
`CX q[2],q[1];`
`...`

However when I try to run qiskit to parse it, it throws the error:
"  File "/Users/anaconda2/envs/qc/lib/python3.6/site-packages/qiskit/converters/ast_to_dag.py", line 294, in _process_node
    self.dag.apply_operation_back(UBase(*args, element), self.condition)
TypeError: __init__() takes 4 positional arguments but 5 were given"

The parsing code i use is like below:
`qc = QuantumCircuit.from_qasm_file(fn)`

It seems qiskit cannot parse U gate as it said there were 5 parameters provided when asked for 4.

**Comment by hillmich** [comment]
Hi ZchiPitt,

I changed U to U3 in the referenced commit, could you try again and tell us if it helped?

Cheers,
Stefan

**Comment by ZchiPitt** [comment]
thanks, i changed it to "u3" and also changed QASMparser.cpp that has "U" before, and it works now
