### ISSUE TITLE
The problem in generating an output file 

### ISSUE THREAD

**Issue by midiareshadi** [iic-jku/ibm_qx_mapping#5]
Hi,
I have compiled the commit on **Nov 26, 2019,** with id '_490beb7_' on Mint 19.2 (with CMake 3.10.2 and g++-7) with no error.
The 'dd_example' file (executive file in build folder) is executed only by determinig an input file :
./dd_example <input_file> 
after running this command, I can see the results of mapping on terminal including elementary gates,  depth,...
but with passing an ouput file to _'dd_example'_ command (./dd_example <input_file> <output_file>) I get the _'Usage: ./dd_example <input_file>'_ message in terminal. 
So, I write this issue to report the problem of making output file in '_490beb7_' commit.
Thanks in advance for your attention.

Midia

**Comment by hillmich** [comment]
Hi,
to enable the output of the resulting circuit you have to set the macro `DUMP_MAPPED_CIRCUIT` to 1 ([main.cpp:15 in the current commit](https://github.com/iic-jku/ibm_qx_mapping/blob/490beb705a2be5b8df2a4a1128b04c8d337ecce3/src/main.cpp#L15)).

Afterwards the program requires two parameters (input file and output file) so you can use it as you intended. 

Cheers,
Stefan

**Comment by midiareshadi** [comment]
Hi Stefan,
Thank you so much for your fast reply. I set that macro to 1 and the output_file is created. 

Thanks again,
Midia
