### ISSUE TITLE
Questions about CNOT direction in IBM QX5 coupling map

### ISSUE THREAD

**Issue by sunghyepark** [iic-jku/ibm_qx_mapping#6]
Dear iic-jku,

Greetings,
My name is Sunghye Park. Currently, I am a master student at POSTECH in Korea.

Since I want to understand your mapping methodology, I've installed a ibm_qx_mapping simulator as your build guide.

But, there is  2 errors during the 'make' in 'build' directory.
Such as 

           error: no matching function for call to 'edge::edge(int&, int)'
             _M_value_field(std::forward<_Args>(__args)...) { }

So, I could solve the error by adding the following code to the part of  'edge' struct in the main.cpp in the src directory.

           struct edge {
                  int v1;
                  int v2;
   
                  edge () {
                  }
                  edge (int a, int b): v1 (a), v2 (b) {
                  }
              };

However, when I modified and run the code above, the direction of CNOT gate did not match the direction of the IBM QX5 graph. (For example, Q1 should control Q0, but Q0 controls Q1)

So, I am wondering how I can fix this error in the main.cpp.
I would appreciate your reply.

Best Regards,
Sunghye Park

**Comment by hillmich** [comment]
Hi,

could you give us more information about the error(s) and the compiler you are using?
I just compiled the project without problems.

Regarding your issue with the direction of the CNOT gate: Did you change the architecture to to IBM QX5? (The default is Linear Nearest Neighbor and I have to admin this is not well-reflected in the documentation.)

**Comment by sunghyepark** [comment]
As you told me about setting the architecture to the IBM QX5, architecture in the main code is well set up so the direction of the CNOT gate is no problem.

And the error came out like this at first, 

           /home/shpark/Quantum/Bench_of_quantum_circuit/ibm_qx_mapping/src/main.cpp:108:29:   required from here

           /usr/include/c++/4.8.2/bits/stl_tree.h:140:49: error: no matching function for call to 'edge::edge(int&, int)'
               _M_value_field(std::forward<_Args>(__args)...) { }
                                                            ^

           /usr/include/c++/4.8.2/bits/stl_tree.h:140:49: error: no matching function for call to 'edge::edge(int, int&)'
               _M_value_field(std::forward<_Args>(__args)...) { }
                                                            ^

But, it seems to be because I downloaded the previous version of the git code. 
There was a problem in the 'graph.emplace' part of build_graph_NN, but the latest version has been fixed so that no error occurs.

Thank you once again for everything you've done.

**Comment by hillmich** [comment]
Happy to help :)
