### ISSUE TITLE
examples not working

### ISSUE THREAD

**Issue by fgfuchs** [iic-jku/ibm_qx_mapping#7]
I get the following error message:

```
 ./build/dd_example examples/one-two-three-v1_99.qasm            
Failed to open file 'qelib1.inc'!
Undefined gate: x
Undefined gate: q
ERROR: unexpected statement: started with [!

```
Am I doing something wrong?

**Comment by hillmich** [comment]
Yeah, you have to include the `qelib1.inc` from IBM's Qiskit.

Given that this file is under an open license, I included it in this repo. So if you pull, the error should go away. (Additionally, I updated the cmake file: Now the executable is really called `ibm_qx_mapping`).

**Comment by fgfuchs** [comment]
Thank you for the fast response. Did you forget to push your changes? Anyway, I include the file myself and it worked.

**Comment by hillmich** [comment]
Yeah, I forgot :sweat_smile: 
But I'm glad it works for you anyway :)
